### PR TITLE
fix: better error message

### PR DESCRIPTION
**Pull request by dan-online**

### CODE REVIEW

**Review by RealShadowNova — COMMENTED** [review]
Why?

**Comment by dan-online** [comment]
The current error output is just "MapProviderError" or something like that, in the providers we don't have a message passed to the error at all so it is unclear what is happening

**Comment by dan-online** [comment]
Alternatively, we could use a similar method to ``core`` with ``resolveIdentifier`` so the messages are formatted

**Review by RealShadowNova — COMMENTED** [review]
I personally just don't like this. Maybe better formatting is needed here. I do see where it would be useful for logging. Are you certain that `method` and `identifier` don't show up in logs?

**Comment by RealShadowNova** [comment]
Resolved by #58

**Pull request closed without merging**
